# Generated by Django 4.1.7 on 2023-03-21 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_narrativedashboardpagedownloads_download_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="narrativedashboardpage",
            name="download_report_body",
        ),
        migrations.RemoveField(
            model_name="narrativedashboardpage",
            name="download_report_button_text",
        ),
        migrations.RemoveField(
            model_name="narrativedashboardpage",
            name="download_report_cover",
        ),
        migrations.RemoveField(
            model_name="narrativedashboardpage",
            name="download_report_title",
        ),
        migrations.RemoveField(
            model_name="narrativedashboardpage",
            name="report_download",
        ),
    ]
