name: APHRC Dashboard CD

on:
  push:
    tags:
      - "*"
    branches:
      - "dev"
  pull_request:
    branches:
      - "*"

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set env for develop branch
      if: endsWith(github.ref, '/dev')
      run: |
        echo "MASINDI_HOST=${{ secrets.MASINDI_DEV_HOST }}" >> $GITHUB_ENV
        echo "MASINDI_USERNAME=${{ secrets.MASINDI_DEV_USER }}" >> $GITHUB_ENV
        echo "MASINDI_SITE_URL=masindi.datahub.go.ug" >> $GITHUB_ENV
        echo "REPO_PATH=~/git/ug-district-datahub" >> $GITHUB_ENV

    - name: Pull latest repo updates to server
      if: endsWith(github.ref, '/dev')
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.MASINDI_HOST }}
        username: ${{ env.MASINDI_USERNAME }}
        key: ${{ secrets.MASINDI_KEY }}
        port: ${{ secrets.MASINDI_PORT }}
        command_timeout: 30m
        script: |
          cd ${{ env.REPO_PATH }}
          git stash
          git fetch --all --prune
          git checkout dev
          git pull

    - name: Deploy dev branch
      if: endsWith(github.ref, '/dev')
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.MASINDI_HOST }}
        username: ${{ env.MASINDI_USERNAME }}
        key: ${{ secrets.MASINDI_KEY }}
        port: ${{ secrets.MASINDI_PORT }}
        command_timeout: 30m
        script: |
          cd ${{ env.REPO_PATH }}
          echo "SITE_URL=masindi.datahub.go.ug" > .env.nginx
          chmod 700 "deploy_script.sh"
          ./deploy_script.sh
